# Generated by Django 5.1.6 on 2025-06-11 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Robot İsmi')),
                ('product_name', models.CharField(max_length=150, verbose_name='Ürün İsmi')),
                ('yaratilma_zamani', models.DateTimeField(auto_now_add=True)),
                ('guncellenme_zamani', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Robotlar',
            },
        ),
        migrations.CreateModel(
            name='RobotDurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Beklemede'), ('working', 'Çalışıyor'), ('charging', 'Şarj Oluyor'), ('maintenance', 'Bakımda'), ('error', 'Hata')], default='idle', max_length=20)),
                ('durum_mesaji', models.CharField(max_length=240)),
                ('battery_level', models.IntegerField(default=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('yaratilma_zamani', models.DateTimeField(auto_now_add=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durum_mesajlari', to='robots.robot')),
            ],
            options={
                'verbose_name_plural': 'Robot Durum Mesajları',
                'ordering': ['-yaratilma_zamani'],
            },
        ),
        migrations.CreateModel(
            name='RobotPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_dosyasi', models.FileField(upload_to='robot_pdfs/%Y/%m/', verbose_name='PDF Dosyası')),
                ('dosya_adi', models.CharField(blank=True, max_length=200, verbose_name='Dosya Adı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('yukleme_zamani', models.DateTimeField(auto_now_add=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_dosyalari', to='robots.robot')),
            ],
            options={
                'verbose_name_plural': 'Robot PDF Dosyaları',
                'ordering': ['-yukleme_zamani'],
            },
        ),
    ]
