# Generated by Django 5.1.6 on 2025-06-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RobotDurum',
        ),
    ]
