# Generated by Django 5.1.6 on 2025-06-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_delete_robotdurum'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotpdf',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
    ]
