# Generated by Django 5.1.6 on 2025-06-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_robotpdf_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robot',
            options={'ordering': ['-yaratilma_zamani'], 'verbose_name': 'Robot', 'verbose_name_plural': 'Robotlar'},
        ),
        migrations.AlterModelOptions(
            name='robotpdf',
            options={'ordering': ['-yukleme_zamani'], 'verbose_name': 'Robot PDF Dosyası', 'verbose_name_plural': 'Robot PDF Dosyaları'},
        ),
    ]
