# Generated by Django 5.1.6 on 2025-06-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0004_alter_robot_options_alter_robotpdf_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotpdf',
            name='has_role',
            field=models.BooleanField(default=False, verbose_name="Rol PDF'i mi?"),
        ),
        migrations.AddField(
            model_name='robotpdf',
            name='has_rules',
            field=models.BooleanField(default=False, verbose_name="Kurallar PDF'i mi?"),
        ),
    ]
