# Generated by Django 5.1.6 on 2025-06-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0005_robotpdf_has_role_robotpdf_has_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotpdf',
            name='pdf_type',
            field=models.CharField(choices=[('bilgi', 'Bilgi'), ('kural', 'Kural'), ('rol', 'Rol')], default='bilgi', max_length=10, verbose_name='PDF Türü'),
        ),
    ]
