# Generated by Django 5.1.6 on 2025-06-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0006_add_pdf_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotpdf',
            name='has_info',
            field=models.BooleanField(default=False, verbose_name="Bilgi PDF'i mi?"),
        ),
    ]
