# Generated by Django 5.1.6 on 2025-06-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0013_add_package_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='paket_turu',
            field=models.CharField(choices=[('basic', 'Temel Paket'), ('standard', 'Standart Paket'), ('premium', 'Premium Paket')], default='basic', max_length=10, verbose_name='Paket Türü'),
        ),
    ]
