# Generated by Django 5.1.6 on 2025-06-16 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0014_add_brand_to_robot'),
        ('robots', '0014_alter_brand_paket_turu'),
    ]

    operations = [
    ]
