# Generated by Django 5.1.6 on 2025-06-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0015_merge_20250616_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='paket_turu',
            field=models.CharField(choices=[('normal', 'Normal Paket'), ('pro', 'Pro Paket'), ('premium', 'Premium Paket')], default='normal', max_length=10, verbose_name='Paket Türü'),
        ),
    ]
