# Generated by Django 5.1.6 on 2025-07-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0016_alter_brand_paket_turu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotpdf',
            name='pdf_dosyasi',
            field=models.URLField(max_length=500, verbose_name='PDF Dosyası (Google Drive Linki)'),
        ),
    ]
