# Generated by Django 5.1.6 on 2025-07-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0017_alter_robotpdf_pdf_dosyasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotpdf',
            name='gdrive_file_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Google Drive Dosya ID'),
        ),
        migrations.AddField(
            model_name='robotpdf',
            name='supabase_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Supabase Dosya Yolu'),
        ),
    ]
