# Generated by Django 5.1.6 on 2025-07-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0018_robotpdf_gdrive_file_id_robotpdf_supabase_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotpdf',
            name='pdf_icerigi',
            field=models.TextField(blank=True, null=True, verbose_name='PDF İçeriği'),
        ),
    ]
