# Generated by Django 5.1.6 on 2025-07-09 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0019_robotpdf_pdf_icerigi'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotSystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('main', 'Ana Sistem Prompt'), ('health_claims', 'Sağlık Beyanları'), ('product_redirect', 'Ürün Yönlendirme'), ('fallback', 'Fallback/Varsayılan')], default='main', max_length=20, verbose_name='Prompt Türü')),
                ('prompt_content', models.TextField(verbose_name='Prompt İçeriği')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('priority', models.IntegerField(default=0, verbose_name='Öncelik (Yüksek önce)')),
                ('topic_keywords', models.TextField(blank=True, help_text='Virgülle ayrılmış anahtar kelimeler (örn: bağışıklık,yorgunluk,kas)', null=True, verbose_name='Konu Anahtar Kelimeleri')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_prompts', to='robots.robot', verbose_name='Robot')),
            ],
            options={
                'verbose_name': 'Robot Sistem Prompt',
                'verbose_name_plural': 'Robot Sistem Promptları',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='robotsystemprompt',
            unique_together={('robot', 'prompt_type')},
        ),
    ]
