# Generated by Django 5.1.6 on 2025-07-10 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0021_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text="Frontend'den gelen unique session ID", max_length=100, verbose_name='Oturum ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Zamanı')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('total_messages', models.PositiveIntegerField(default=0, verbose_name='Toplam Mesaj Sayısı')),
                ('total_response_time', models.DecimalField(decimal_places=3, default=0.0, max_digits=10, verbose_name='Toplam Yanıt Süresi (saniye)')),
                ('average_response_time', models.DecimalField(decimal_places=3, default=0.0, max_digits=8, verbose_name='Ortalama Yanıt Süresi (saniye)')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Kullanıcı IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='robots.robot', verbose_name='Robot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Chat Oturumu',
                'verbose_name_plural': 'Chat Oturumları',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'Kullanıcı Mesajı'), ('assistant', 'AI Yanıtı')], max_length=10, verbose_name='Mesaj Türü')),
                ('user_message', models.TextField(verbose_name='Kullanıcı Mesajı')),
                ('ai_response', models.TextField(blank=True, null=True, verbose_name='AI Yanıtı')),
                ('response_time', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Yanıt Süresi (saniye)')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='İşlem Başlangıç Zamanı')),
                ('processing_ended_at', models.DateTimeField(blank=True, null=True, verbose_name='İşlem Bitiş Zamanı')),
                ('status', models.CharField(choices=[('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız'), ('timeout', 'Zaman Aşımı')], default='processing', max_length=15, verbose_name='Durum')),
                ('ai_model_used', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kullanılan AI Modeli')),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kullanılan Token Sayısı')),
                ('optimization_enabled', models.BooleanField(default=False, verbose_name='Optimizasyon Açık mıydı?')),
                ('context_used', models.BooleanField(default=False, verbose_name='Context Kullanıldı mı?')),
                ('context_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Context Boyutu (karakter)')),
                ('citations_count', models.PositiveIntegerField(default=0, verbose_name='Alıntı Sayısı')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Hata Mesajı')),
                ('error_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hata Türü')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('user_feedback', models.IntegerField(blank=True, choices=[(1, '👎 Kötü'), (2, '😐 Orta'), (3, '👍 İyi')], null=True, verbose_name='Kullanıcı Geri Bildirimi')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Admin Notları')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='robots.robot', verbose_name='Robot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='robots.chatsession', verbose_name='Chat Oturumu')),
            ],
            options={
                'verbose_name': 'Chat Mesajı',
                'verbose_name_plural': 'Chat Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user', 'robot', 'started_at'], name='robots_chat_user_id_1b244c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['session_id'], name='robots_chat_session_b3dfe6_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['started_at'], name='robots_chat_started_cf35d8_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['user', 'robot', 'created_at'], name='robots_chat_user_id_9d723c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='robots_chat_session_39df91_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['status'], name='robots_chat_status_b760b2_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['response_time'], name='robots_chat_respons_eab412_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='robots_chat_created_8840dd_idx'),
        ),
    ]
