# Generated by Django 5.1.6 on 2025-07-07 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL Slug')),
                ('brand', models.CharField(default='SIDREX®', max_length=100, verbose_name='Marka')),
                ('price', models.CharField(max_length=50, verbose_name='Fiyat')),
                ('original_price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Eski Fiyat')),
                ('rating', models.IntegerField(default=5, verbose_name='Puan')),
                ('review_count', models.IntegerField(default=0, verbose_name='Değerlendirme Sayısı')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('ingredients', models.TextField(verbose_name='İçerik')),
                ('usage', models.TextField(verbose_name='Kullanım')),
                ('warnings', models.TextField(verbose_name='Uyarılar')),
                ('bg_color', models.CharField(default='bg-gray-50', max_length=50, verbose_name='Arka Plan Rengi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255, verbose_name='Özellik')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product')),
            ],
            options={
                'verbose_name': 'Ürün Özelliği',
                'verbose_name_plural': 'Ürün Özellikleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_path', models.CharField(max_length=1024, verbose_name='Supabase Yolu')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ana Resim')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt Metin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Ürün Resmi',
                'verbose_name_plural': 'Ürün Resimleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('rating', models.IntegerField(verbose_name='Puan')),
                ('comment', models.TextField(verbose_name='Yorum')),
                ('date', models.CharField(max_length=50, verbose_name='Tarih')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'verbose_name': 'Ürün Yorumu',
                'verbose_name_plural': 'Ürün Yorumları',
                'ordering': ['order'],
            },
        ),
    ]
