# Generated by Django 5.1.6 on 2025-07-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(help_text='Medyanın adı', max_length=255)),
                ('supabase_path', models.CharField(blank=True, max_length=1024)),
                ('yuklenme_tarihi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medya Dosyası',
                'verbose_name_plural': 'Medya Dosyaları',
            },
        ),
        migrations.CreateModel(
            name='StatikVarlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anahtar', models.CharField(db_index=True, help_text='Varlığı kod içinde çağırmak için kullanılacak benzersiz anahtar.', max_length=100, unique=True)),
                ('supabase_path', models.CharField(help_text='Supabase bucket içindeki tam dosya yolu.', max_length=1024)),
                ('aciklama', models.TextField(blank=True, help_text='Bu varlığın nerede ve ne için kullanıldığı.', null=True)),
            ],
            options={
                'verbose_name': 'Statik Varlık',
                'verbose_name_plural': 'Statik Varlıklar',
            },
        ),
    ]
