# Generated by Django 5.1.6 on 2025-07-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medya', '0001_initial'),
    ]

    operations = [
    ]
